---
collections:
  - name: geerlingguy.security
    version: 2.4.0
    source: https://galaxy.ansible.com
    src: https://github.com/geerlingguy/ansible-role-security.git
    scm: git
  - name: geerlingguy.nfs
    version: 2.1.0
    source: https://galaxy.ansible.com
    src: https://github.com/geerlingguy/ansible-role-nfs.git
    scm: git