---
security_sudoers_passwordless:
  - "{{ ansible_user }}"

samba_daemon: smbd

# These variables must be defined per-host, in host_vars.
# zfs_pools: []
# zfs_samba_shares: []
# sanoid_conf: ""

# Ownership for the samba share directories.
zfs_samba_owner: "{{ ansible_user }}"
zfs_samba_group: sudo
