---
- hosts: nas
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  roles:
    # - name: geerlingguy.security
    #   version: 2.4.0
    #   source: https://galaxy.ansible.com
    #   src: https://github.com/geerlingguy/ansible-role-security.git
    #   scm: git
    - name: geerlingguy.nfs
      version: 2.1.0
      source: https://galaxy.ansible.com
      src: https://github.com/geerlingguy/ansible-role-nfs.git
      scm: git
    # - geerlingguy.security
    # - geerlingguy.nfs
    # - geerlingguy.samba
    # - geerlingguy.sanoid

  # collections:
  #   - name: geerlingguy.security
  #     version: 2.4.0
  #     source: https://galaxy.ansible.com
  #   - name: geerlingguy.nfs
  #     version: 2.1.0
  #     source: https://galaxy.ansible.com

  tasks:
    - name: Install ZFS and prerequisites.
      ansible.builtin.package:
        name:
          - linux-headers-generic
          - zfs-dkms
          - zfsutils-linux
          - samba
      tags: ['zfs']

    - name: Create ZFS pools.
      ansible.builtin.command:
        cmd: zpool create {{ item.name }} {{ item.members }} -f
        creates: /{{ item.name }}
      loop: "{{ zfs_pools }}"
      tags: ['zfs']

    # - name: Create volumes for Samba shares.
    #   community.general.zfs:
    #     name: "{{ item.name }}"
    #     state: present
    #     extra_zfs_properties: "{{ item.extra_zfs_properties }}"
    #   loop: "{{ zfs_samba_shares }}"
    #   tags: ['zfs', 'samba']

    # - name: Configure Samba shares.
    #   include_tasks: tasks/samba.yml

    # - name: Configure user for ZFS replication.
    #   include_tasks: tasks/replication.yml

    # - name: Set up rclone.
    #   include_tasks: tasks/rclone.yml
