---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  roles:
    - geerlingguy.security
    - geerlingguy.samba

  handlers:
    - name: restart samba
      ansible.builtin.service:
        name: smbd
        state: restarted

  tasks:
    - name: Install ZFS and prerequisites
      ansible.builtin.package:
        name:
          - linux-headers-generic
          - zfs-dkms
          - zfsutils-linux
          - samba
      tags: ['zfs']

    - name: Create ZFS pool of HDDs
      ansible.builtin.command:
        cmd: zpool create {{ zfs_pool_name }} raidz2 {{ zfs_pool_members | join(' ') }} -f
        creates: /{{ zfs_pool_name }}
