---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  roles:
    - geerlingguy.security
    - geerlingguy.samba
    - geerlingguy.sanoid

  tasks:
    - name: Configure user accounts.
      include_tasks: tasks/users.yml

    - name: Install ZFS and prerequisites.
      ansible.builtin.package:
        name:
          - linux-headers-generic
          - zfs-dkms
          - zfsutils-linux
          - samba
      tags: ['zfs']

    - name: Create ZFS pools.
      ansible.builtin.command:
        cmd: zpool create {{ item.name }} {{ item.members }} -f
        creates: /{{ item.name }}
      loop: "{{ zfs_pools }}"
      tags: ['zfs']

    - name: Create volumes for Samba shares.
      community.general.zfs:
        name: "{{ item.name }}"
        state: present
        extra_zfs_properties: "{{ item.extra_zfs_properties }}"
      loop: "{{ zfs_samba_shares }}"
      tags: ['zfs', 'samba']

    - name: Configure Samba shares.
      include_tasks: tasks/samba.yml

    - name: Configure user for ZFS replication.
      include_tasks: tasks/replication.yml

    # - name: Set up rclone.
    #   include_tasks: tasks/rclone.yml
