---
- name: Configure Samba.
  community.general.ini_file:
    path: /etc/samba/smb.conf
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: false
    mode: 0644
  loop:
    - { option: usershare path, value: /var/lib/samba/usershares }
    - { option: usershare max shares, value: 100 }
    - { option: usershare allow guests, value: 'yes' }
    - { option: usershare owner only, value: 'no' }
    - { option: vfs objects, value: 'catia fruit streams_xattr' }
    - { option: fruit:nfs_aces, value: 'no' }
  notify: restart smb
  tags: ['samba']

- name: Configure Samba usershares.
  ansible.builtin.template:
    src: templates/smb-share.conf.j2
    dest: /var/lib/samba/usershares/{{ item.smb_share_name }}
    owner: root
    group: root
    mode: 0644
  loop: "{{ zfs_samba_shares }}"
  notify: restart smb
  tags: ['samba']

- name: Configure ownership on Samba shares.
  ansible.builtin.file:
    path: "/{{ item.name }}"
    state: directory
    owner: "{{ zfs_samba_owner }}"
    group: "{{ zfs_samba_group }}"
    mode: 0775
  loop: "{{ zfs_samba_shares }}"
  tags: ['samba']

# TODO: See https://stackoverflow.com/a/46428282/100134
# For now, manually run `sudo smbpasswd -a jgeerling`
- name: Configure Samba passwords (not yet implemented).
  ansible.builtin.meta: noop
  tags: ['samba']
